name: Publish

on:
  push:
    branches:
      - master

jobs:

  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Setup node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          # Fetch all git history for changesets
          fetch-depth: 0

      - name: Git - pull tags
        run: |
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: PNPM setup
        uses: pnpm/action-setup@v1.2.0
        with:
          version: ${{secrets.PNPM_VERSION}}
          run_install: |
            - recursive: false

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@master
        with:
          publish: pnpm run publish
          version: pnpm run version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
