name: Verify Commit

on:
  pull_request:
    branches:
      - develop

jobs:

  #lint:

  test:
    name: Test
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    env:
      NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - name: Setup node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Checkout
        uses: actions/checkout@v2
      - name: PNPM setup
        uses: pnpm/action-setup@v1.2.0
        with:
          version: ${{secrets.PNPM_VERSION}}
          run_install: true
      - name: Test - All
        run: pnpm run test:all
